article/urls.py
from django.urls import path
from .views import new, detail, edit, destroy

app_name = 'article'

urlpatterns = [
  path("new", new, name='new'),
  path("<int:id>", detail, name='detail'),
  path("edit/<int:id>", edit, name='edit'),
  path("destroy/<int:id>", destroy, name='destroy')
]

main/urls.py
from django.urls import path
from .views import index

app_name = 'main'

urlpatterns = [
    path("", index, name='index'),
]

serengeti/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('main.urls')),
    path("users/", include('user.urls')),
    path("articles/", include('article.urls')),
]

user/urls.py
from django.urls import path
from .views import signin, signup, signout

app_name = 'user'

urlpatterns = [
  path("signin/", signin, name='signin'),
  path("signup/", signup, name='signup'),
  path("signout/", signout, name='signout'),
]

article/models.py
from django.db import models

class Article(models.Model):
  author = models.ForeignKey(
    'user.User',
    on_delete=models.CASCADE,
  )

  title = models.TextField()
  content = models.TextField()

  created_at = models.DateTimeField(
    auto_now_add=True,
  )
  
  updated_at = models.DateTimeField(
    auto_now=True,
  )

main/models.py
from django.db import models

# Create your models here.

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin

class UserManager(BaseUserManager):
    
    def _create_user(self, username, password, **kwargs):
        user = self.model(
            username = username,
            **kwargs
        )
        user.set_password(password)
        user.save()        

    def create_user(self, username, password, **kwargs):
        self._create_user(username, password, **kwargs)

    def create_superuser(self, username, password, **kwargs):
        kwargs.setdefault('is_superuser', True)
        self._create_user(username, password, **kwargs)

class User(AbstractBaseUser, PermissionsMixin):
    
    USERNAME_FIELD = 'username'
    
    username = models.CharField(
        unique=True,
        max_length=20,
    )

    created_at = models.DateTimeField(
        auto_now_add = True,
    )

    updated_at = models.DateTimeField(
        auto_now = True,
    )

    objects = UserManager()
    
    @property
    def is_staff(self):
      return self.is_superuser

article/forms.py
from django import forms
from .models import Article


class ArticleForm(forms.ModelForm):
   class Meta:
      model = Article
      fields = [
         'title', 
         'content',
        #  'author'
      ]

user/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms import TextInput
from django import forms
from .models import User

class UserLoginForm(AuthenticationForm):
    username = forms.CharField(
        widget = forms.TextInput(attrs={'class': 'form-control', 'style': 'background-color: skyblue;'}),
        label='유저이름'
    )


class UserSignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User

        fields = [
            'username'
        ]

        widgets = {
          'username': TextInput(attrs={
            'class': "form-control",
            'style': 'background-color: skyblue;',
            'placeholder': 'ID'
          }),
        }

        labels = {
          'username': 'ID',
        }

article/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ArticleForm
from .models import Article


def new(request):
    form = ArticleForm()

    if request.method == 'POST':
        form = ArticleForm(request.POST)

        if form.is_valid():
            article = form.save(
                commit = False
            )

            article.author = request.user
            article.save()
            return redirect('article:detail', id=article.id)
        
    return render(request, 'new.html', {'form': form})


def detail(request, id):
    article = get_object_or_404(Article, pk=id)

    return render(request, 'detail.html', {'article': article})


def edit(request, id):
    article = get_object_or_404(Article, pk=id)

    form = ArticleForm(instance=article)

    if request.method == 'POST':
      form = ArticleForm(request.POST, instance=article)

      if form.is_valid():
        article = form.save()

        return redirect('article:detail', id=article.id)

    return render(request, 'edit.html', {'form': form, 'article': article})


def destroy(request, id):
   article = get_object_or_404(Article, pk=id)

   article.delete()

   return redirect('main:index')

main/views.py
from django.shortcuts import render
from article.models import Article
from django.core.paginator import Paginator

def index(request):
  articles = Article.objects.all()
  paginator = Paginator(articles, 5)
  page_number = request.GET.get('page')
  page_obj = paginator.get_page(page_number)
  return render(request, 'index.html', {'page_obj': page_obj})

user/views.py
from django.shortcuts import render, redirect
from .forms import UserLoginForm, UserSignUpForm
from django.contrib.auth import login, logout

def signin(request):
  form = UserLoginForm()

  if request.method == 'POST':
    form = UserLoginForm(request, request.POST)

    if form.is_valid():
      login(request, form.get_user())
      return redirect('main:index')

  return render(request, 'signin.html', {'form': form})


def signup(request):

  form = UserSignUpForm()

  if request.method == 'POST':
    form = UserSignUpForm(request.POST)

    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('main:index')
    
  return render(request, 'signup.html', {'form': form})


def signout(request):
  logout(request)
  return redirect('main:index')

article/templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  글 자세히 보기 <br>
  id : {{article.id}} <br>
  <h1>{{article.title}}</h1>
  <p>
    {{article.content}}
  </p>
  <a href="{% url 'main:index' %}">홈으로</a>
</body>
</html>

article/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <form action="{% url 'article:edit' id=article.id %}" method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">글 수정</button>
  </form>
</body>
</html>

article/templates/new.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <form action="{% url 'article:new' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">글 작성</button>
  </form>
</body>
</html>

main/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    메인 페이지 <br>

    {% if user.is_authenticated %}
      <a href="{% url 'user:signout' %}">로그아웃</a> <br>
      <a href="{% url 'article:new' %}">글 작성</a>
    {% else %}
      <a href="{% url 'user:signin' %}">로그인</a> <br>
      <a href="{% url 'user:signup' %}">회원가입</a>
    {% endif %}

    <hr>

    {% for article in page_obj %}
      <div>
        <a href="{%url 'article:detail' id=article.id %}">{{article.title}}</a>        
        {{article.content}}
        {{article.author.username}}

        <a href="{% url 'article:edit' id=article.id %}">글 수정</a>
        <a href="{% url 'article:destroy' id=article.id %}">글 삭제</a>
      </div>
    {% endfor %}
    <span>
      <hr>
      {%if page_obj.has_previous %}
      <a href="?page=1">처음으로</a>
      <a href="?page={{ page_obj.previous_page_number }}">이전</a>
      {% endif %}

      {% for page_number in page_obj.paginator.page_range %}
      {% if page_number == page_obj.number %}

      <a href="?&page={{ page_number }}">{{ page_number }}</a>

      {% else %}

      <a href="?&page={{ page_number }}">{{ page_number }}</a>

      {% endif %}
      {% endfor %}

      {%if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}">다음</a>
      <a href="?page={{ page_obj.paginator.num_pages }}">마지막으로</a>
      {% endif %}

      <style>
        body {
          text-align: center;
        }
        
  </span>
  </body>
</html>

user/templates/signin.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  로그인 페이지 <br>
  <form method="post" action="{% url 'user:signin' %}">
    {% csrf_token %}

    {{ form }}
    <button type="submit">로그인</button>
  </form>
</body>
</html>

user/templates/signup.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    회원가입 페이지 <br />
    <form method='post' action="{% url 'user:signup' %}">
      {% csrf_token %}
      {{ form }}
      <button type="submit">회원 가입</button>
    </form>
  </body>
</html>